Updated protobuf discovery for linux
dev-osrose/osIROSE-new pull request #102
Opened 2017-08-06 18:03 UTC by L3nn0x

I still had problems when detecting protobuf on linux, because cmake prefers the system-wide one over the local one. And I have v3.3.2 system-wide while we're using v3.1.0 in the project, and they aren't compatible. The other small modification is because emacs creates temp files while working on them by appending `.#` in front of the name. ( Ex: `main.cpp` becomes `.#main.cpp`) And that's picked up by the regex in the test cmake. If you have an idea to improve my quick fix :)

2017-08-09 19:30 UTC, RavenX8 requested changes

2017-08-09 19:30 UTC, RavenX8 commented on CMakeLists.txt
> +    set(PROTOBUF_PROTOC_EXECUTABLE "${PROTOBUF_ROOT}/bin/protoc" CACHE STRING "${PROTOBUF_ROOT}/bin/protoc" FORCE)
This will cause the cmake module to not look for protobuf at all. If it still can't find protoc in the 3rdParty folder, I suggest running cmake with the -DBUILD_PROTOBUF=ON directive. Try that first.

2017-08-11 16:37 UTC, L3nn0x commented on CMakeLists.txt
> +    set(PROTOBUF_PROTOC_EXECUTABLE "${PROTOBUF_ROOT}/bin/protoc" CACHE STRING "${PROTOBUF_ROOT}/bin/protoc" FORCE)
Yup you're right, that's definitely not the correct way to do things.

2017-08-11 16:37 UTC, L3nn0x commented
As we're removing protobuf, this branch isn't of actuality anymore, so I'm closing it.

2017-08-11 16:37 UTC, closed without merging